import type { ContentMetadata } from './types';

// Ajak Main canonical metadata (51 items). Additive, runtime-inert. Generated — do not hand-edit.
export const AJAK_MAIN_METADATA: ContentMetadata[] = [
  {
    content_id: 'am-001', legacy_id: 'am-001', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 12 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Locomotion and Moving Through Space', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-tummy-time', legacy_id: 'am-tummy-time', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 6 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Trunk and Postural Control', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-motorik', legacy_id: 'am-motorik', content_type: 'AJAK_MAIN',
    age_range: { min_months: 7, max_months: 18 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Locomotion and Moving Through Space', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-object-perm', legacy_id: 'am-object-perm', content_type: 'AJAK_MAIN',
    age_range: { min_months: 7, max_months: 18 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Object Permanence and Memory', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-kemandirian-praktis', legacy_id: 'am-kemandirian-praktis', content_type: 'AJAK_MAIN',
    age_range: { min_months: 13, max_months: 24 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Growing Independence in Daily Tasks', secondary: [{ domain: 'Adaptive / Self-Help', capability: 'Participating in Self-Care' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-makan-seru', legacy_id: 'am-makan-seru', content_type: 'AJAK_MAIN',
    age_range: { min_months: 13, max_months: 36 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Self-Feeding', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-toilet', legacy_id: 'am-toilet', content_type: 'AJAK_MAIN',
    age_range: { min_months: 19, max_months: 36 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Toileting and Hygiene', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-fungsi-eksekutif', legacy_id: 'am-fungsi-eksekutif', content_type: 'AJAK_MAIN',
    age_range: { min_months: 19, max_months: 36 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Impulse Control and Waiting', secondary: [{ domain: 'Language & Communication', capability: 'Receptive Language' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-pilih-sendiri', legacy_id: 'am-pilih-sendiri', content_type: 'AJAK_MAIN',
    age_range: { min_months: 25, max_months: 36 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Decision-Making and Choice-Making', secondary: [{ domain: 'Social-Emotional', capability: 'Autonomy and Sense of Agency' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-003', legacy_id: 'am-003', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 12 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Empathy and Understanding Others', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-senyum-balas', legacy_id: 'am-senyum-balas', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 6 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Attachment and Secure Relationship', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-kelekatan', legacy_id: 'am-kelekatan', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 12 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Attachment and Secure Relationship', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-joint-attention', legacy_id: 'am-joint-attention', content_type: 'AJAK_MAIN',
    age_range: { min_months: 7, max_months: 18 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Gestures and Nonverbal Communication', secondary: [{ domain: 'Social-Emotional', capability: 'Social Interaction and Play with Others' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-temperamen', legacy_id: 'am-temperamen', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 36 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'LOW' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS', parenting_practice_candidate: false, candidate_content_type: null,
  },
  {
    content_id: 'am-keterampilan-sosial', legacy_id: 'am-keterampilan-sosial', content_type: 'AJAK_MAIN',
    age_range: { min_months: 19, max_months: 36 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Empathy and Understanding Others', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-disiplin-empati', legacy_id: 'am-disiplin-empati', content_type: 'AJAK_MAIN',
    age_range: { min_months: 13, max_months: 24 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'LOW' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS', parenting_practice_candidate: true, candidate_content_type: 'PARENTING_PRACTICE',
  },
  {
    content_id: 'am-genggam', legacy_id: 'am-genggam', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 6 },
    development: { primary_domain: 'Fine Motor', primary_capability: 'Grasping and Reaching', secondary: [{ domain: 'Gross Motor', capability: 'Sensory and Body Awareness' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-pilihan-kecil', legacy_id: 'am-pilihan-kecil', content_type: 'AJAK_MAIN',
    age_range: { min_months: 7, max_months: 18 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Decision-Making and Choice-Making', secondary: [{ domain: 'Social-Emotional', capability: 'Autonomy and Sense of Agency' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-coba-lagi', legacy_id: 'am-coba-lagi', content_type: 'AJAK_MAIN',
    age_range: { min_months: 7, max_months: 18 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Emotional Regulation', secondary: [{ domain: 'Social-Emotional', capability: 'Autonomy and Sense of Agency' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-pujian-proses', legacy_id: 'am-pujian-proses', content_type: 'AJAK_MAIN',
    age_range: { min_months: 13, max_months: 36 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'LOW' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS', parenting_practice_candidate: true, candidate_content_type: 'PARENTING_PRACTICE',
  },
  {
    content_id: 'am-bebas-mencoba', legacy_id: 'am-bebas-mencoba', content_type: 'AJAK_MAIN',
    age_range: { min_months: 19, max_months: 36 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Autonomy and Sense of Agency', secondary: [{ domain: 'Cognitive', capability: 'Problem Solving' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-rutinitas', legacy_id: 'am-rutinitas', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 12 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'LOW' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS', parenting_practice_candidate: true, candidate_content_type: 'PARENTING_PRACTICE',
  },
  {
    content_id: 'am-ko-regulasi', legacy_id: 'am-ko-regulasi', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 18 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'LOW' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS', parenting_practice_candidate: true, candidate_content_type: 'PARENTING_PRACTICE',
  },
  {
    content_id: 'am-tantrum', legacy_id: 'am-tantrum', content_type: 'AJAK_MAIN',
    age_range: { min_months: 13, max_months: 36 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Emotional Regulation', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-nama-perasaan', legacy_id: 'am-nama-perasaan', content_type: 'AJAK_MAIN',
    age_range: { min_months: 13, max_months: 24 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Emotional Regulation', secondary: [{ domain: 'Language & Communication', capability: 'Vocabulary Building' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-tidur-sehat', legacy_id: 'am-tidur-sehat', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 36 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Child Health', topic: 'Sleep' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-serve-return', legacy_id: 'am-serve-return', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 12 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Conversation and Turn-Taking', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-002', legacy_id: 'am-002', content_type: 'AJAK_MAIN',
    age_range: { min_months: 7, max_months: 24 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Early Literacy and Storytelling', secondary: [{ domain: 'Language & Communication', capability: 'Vocabulary Building' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-tonggak-bahasa', legacy_id: 'am-tonggak-bahasa', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 24 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Expressive Communication', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-pra-literasi', legacy_id: 'am-pra-literasi', content_type: 'AJAK_MAIN',
    age_range: { min_months: 13, max_months: 36 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Early Literacy and Storytelling', secondary: [{ domain: 'Language & Communication', capability: 'Expressive Communication' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-koneksi-nyata', legacy_id: 'am-koneksi-nyata', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 36 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'LOW' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS', parenting_practice_candidate: true, candidate_content_type: 'PARENTING_PRACTICE',
  },
  {
    content_id: 'am-bercerita-bersama', legacy_id: 'am-bercerita-bersama', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 12 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Expressive Communication', secondary: [{ domain: 'Social-Emotional', capability: 'Attachment and Secure Relationship' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-bermain-paralel', legacy_id: 'am-bermain-paralel', content_type: 'AJAK_MAIN',
    age_range: { min_months: 13, max_months: 24 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-005', legacy_id: 'am-005', content_type: 'AJAK_MAIN',
    age_range: { min_months: 19, max_months: 36 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Symbolic and Pretend Thinking', secondary: [{ domain: 'Social-Emotional', capability: 'Social Interaction and Play with Others' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-giliran', legacy_id: 'am-giliran', content_type: 'AJAK_MAIN',
    age_range: { min_months: 13, max_months: 24 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [{ domain: 'Self-Regulation & Executive Function', capability: 'Impulse Control and Waiting' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-kesiapan-sosial', legacy_id: 'am-kesiapan-sosial', content_type: 'AJAK_MAIN',
    age_range: { min_months: 25, max_months: 36 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-kartu-kontras', legacy_id: 'am-kartu-kontras', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 6 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Attention and Focus', secondary: [{ domain: 'Gross Motor', capability: 'Sensory and Body Awareness' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-lagu-ritmis', legacy_id: 'am-lagu-ritmis', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 6 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Attachment and Secure Relationship', secondary: [{ domain: 'Language & Communication', capability: 'Expressive Communication' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-ciluk-ba', legacy_id: 'am-ciluk-ba', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 12 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Object Permanence and Memory', secondary: [{ domain: 'Social-Emotional', capability: 'Attachment and Secure Relationship' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-meraih-mainan', legacy_id: 'am-meraih-mainan', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 12 },
    development: { primary_domain: 'Fine Motor', primary_capability: 'Hand-Eye Coordination', secondary: [{ domain: 'Fine Motor', capability: 'Grasping and Reaching' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-cermin-bayi', legacy_id: 'am-cermin-bayi', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 12 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Self-Awareness and Identity', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-eksplorasi-tekstur', legacy_id: 'am-eksplorasi-tekstur', content_type: 'AJAK_MAIN',
    age_range: { min_months: 0, max_months: 12 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Sensory and Body Awareness', secondary: [{ domain: 'Fine Motor', capability: 'Grasping and Reaching' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-sebab-akibat', legacy_id: 'am-sebab-akibat', content_type: 'AJAK_MAIN',
    age_range: { min_months: 7, max_months: 12 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Cause-and-Effect Understanding', secondary: [{ domain: 'Fine Motor', capability: 'Manipulating Objects' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-musik-marakas', legacy_id: 'am-musik-marakas', content_type: 'AJAK_MAIN',
    age_range: { min_months: 7, max_months: 18 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [{ domain: 'Fine Motor', capability: 'Manipulating Objects' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-berdiri-merambat', legacy_id: 'am-berdiri-merambat', content_type: 'AJAK_MAIN',
    age_range: { min_months: 7, max_months: 18 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Locomotion and Moving Through Space', secondary: [{ domain: 'Gross Motor', capability: 'Balance and Coordination' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-lukis-jari', legacy_id: 'am-lukis-jari', content_type: 'AJAK_MAIN',
    age_range: { min_months: 7, max_months: 18 },
    development: { primary_domain: 'Fine Motor', primary_capability: 'Early Mark-Making and Drawing', secondary: [{ domain: 'Gross Motor', capability: 'Sensory and Body Awareness' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-menara-balok', legacy_id: 'am-menara-balok', content_type: 'AJAK_MAIN',
    age_range: { min_months: 13, max_months: 24 },
    development: { primary_domain: 'Fine Motor', primary_capability: 'Manipulating Objects', secondary: [{ domain: 'Cognitive', capability: 'Problem Solving' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-coret-bebas', legacy_id: 'am-coret-bebas', content_type: 'AJAK_MAIN',
    age_range: { min_months: 19, max_months: 36 },
    development: { primary_domain: 'Fine Motor', primary_capability: 'Early Mark-Making and Drawing', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-puzzle-sederhana', legacy_id: 'am-puzzle-sederhana', content_type: 'AJAK_MAIN',
    age_range: { min_months: 19, max_months: 36 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Problem Solving', secondary: [{ domain: 'Fine Motor', capability: 'Manipulating Objects' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-messy-play', legacy_id: 'am-messy-play', content_type: 'AJAK_MAIN',
    age_range: { min_months: 19, max_months: 36 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Sensory and Body Awareness', secondary: [{ domain: 'Fine Motor', capability: 'Manipulating Objects' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'am-tendang-bola', legacy_id: 'am-tendang-bola', content_type: 'AJAK_MAIN',
    age_range: { min_months: 25, max_months: 36 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Balance and Coordination', secondary: [{ domain: 'Gross Motor', capability: 'Locomotion and Moving Through Space' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
];
