import type { ContentMetadata } from './types';

// Kebiasaan Baik canonical metadata (57 items). Additive, runtime-inert. Generated — do not hand-edit.
export const KEBIASAAN_BAIK_METADATA: ContentMetadata[] = [
  {
    content_id: 'kb-001', legacy_id: 'sk-00-00', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Attachment and Secure Relationship', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Kasih Sayang', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-002', legacy_id: 'sk-00-01', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Attachment and Secure Relationship', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Kasih Sayang', secondary: ['Sabar'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-003', legacy_id: 'sk-00-02', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Sensory and Body Awareness', secondary: [{ domain: 'Social-Emotional', capability: 'Attachment and Secure Relationship' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Kasih Sayang', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-004', legacy_id: 'sk-00-03', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Conversation and Turn-Taking', secondary: [{ domain: 'Language & Communication', capability: 'Expressive Communication' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Cinta Ilmu', secondary: ['Empati'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-005', legacy_id: 'sk-00-04', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Vocabulary Building', secondary: [], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Hormat pada Sesama', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-006', legacy_id: 'sk-01-00', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Following Simple Routines and Instructions', secondary: [], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Sabar', secondary: ['Kesederhanaan'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-007', legacy_id: 'sk-01-01', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Early Literacy and Storytelling', secondary: [{ domain: 'Cognitive', capability: 'Attention and Focus' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Cinta Ilmu', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-008', legacy_id: 'sk-01-02', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Object Permanence and Memory', secondary: [{ domain: 'Social-Emotional', capability: 'Attachment and Secure Relationship' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Cinta Ilmu', secondary: ['Keberanian'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-009', legacy_id: 'sk-01-03', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Conversation and Turn-Taking', secondary: [{ domain: 'Language & Communication', capability: 'Expressive Communication' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Empati', secondary: ['Kasih Sayang'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-010', legacy_id: 'sk-01-04', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Trunk and Postural Control', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Kemandirian', secondary: ['Keberanian'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-011', legacy_id: 'sk-02-00', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: null },
    family: { primary_value: 'Hormat pada Sesama', secondary: ['Berbagi'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'kb-012', legacy_id: 'sk-02-01', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Syukur', secondary: ['Kesederhanaan'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-013', legacy_id: 'sk-02-02', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Cause-and-Effect Understanding', secondary: [{ domain: 'Fine Motor', capability: 'Manipulating Objects' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Cinta Ilmu', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-014', legacy_id: 'sk-02-03', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Berbagi', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-015', legacy_id: 'sk-02-04', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Locomotion and Moving Through Space', secondary: [{ domain: 'Cognitive', capability: 'Curiosity and Exploration' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Kemandirian', secondary: ['Keberanian'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-016', legacy_id: 'sk-03-00', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Vocabulary Building', secondary: [{ domain: 'Language & Communication', capability: 'Gestures and Nonverbal Communication' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Cinta Ilmu', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-017', legacy_id: 'sk-03-01', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [{ domain: 'Language & Communication', capability: 'Expressive Communication' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Hormat pada Sesama', secondary: ['Berbagi'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-018', legacy_id: 'sk-03-02', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Growing Independence in Daily Tasks', secondary: [{ domain: 'Fine Motor', capability: 'Manipulating Objects' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Kemandirian', secondary: ['Tanggung Jawab'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-019', legacy_id: 'sk-03-03', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Curiosity and Exploration', secondary: [], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Syukur', secondary: ['Cinta Ilmu'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-020', legacy_id: 'sk-03-04', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [{ domain: 'Self-Regulation & Executive Function', capability: 'Impulse Control and Waiting' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Sabar', secondary: ['Berbagi'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-021', legacy_id: 'sk-03-05', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [{ domain: 'Language & Communication', capability: 'Gestures and Nonverbal Communication' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Hormat pada Sesama', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-022', legacy_id: 'sk-04-00', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Participating in Routines and Chores', secondary: [{ domain: 'Fine Motor', capability: 'Manipulating Objects' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Tanggung Jawab', secondary: ['Kemandirian'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-023', legacy_id: 'sk-04-01', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: null },
    family: { primary_value: 'Empati', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'kb-024', legacy_id: 'sk-04-02', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Early Literacy and Storytelling', secondary: [{ domain: 'Language & Communication', capability: 'Vocabulary Building' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Cinta Ilmu', secondary: ['Kasih Sayang'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-025', legacy_id: 'sk-04-03', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Berbagi', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-026', legacy_id: 'sk-04-04', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [{ domain: 'Social-Emotional', capability: 'Autonomy and Sense of Agency' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Hormat pada Sesama', secondary: ['Keberanian'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-027', legacy_id: 'sk-04-05', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Impulse Control and Waiting', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Sabar', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-028', legacy_id: 'sk-05-00', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Expressive Communication', secondary: [{ domain: 'Social-Emotional', capability: 'Social Interaction and Play with Others' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Hormat pada Sesama', secondary: ['Kejujuran'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-029', legacy_id: 'sk-05-01', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Participating in Routines and Chores', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Tanggung Jawab', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-030', legacy_id: 'sk-05-02', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Decision-Making and Choice-Making', secondary: [{ domain: 'Social-Emotional', capability: 'Autonomy and Sense of Agency' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Kemandirian', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-031', legacy_id: 'sk-05-03', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Self-Awareness and Identity', secondary: [{ domain: 'Language & Communication', capability: 'Expressive Communication' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Syukur', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-032', legacy_id: 'sk-05-04', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Participating in Routines and Chores', secondary: [{ domain: 'Social-Emotional', capability: 'Empathy and Understanding Others' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Kasih Sayang', secondary: ['Tanggung Jawab'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-033', legacy_id: 'sk-05-05', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Empathy and Understanding Others', secondary: [{ domain: 'Cognitive', capability: 'Symbolic and Pretend Thinking' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Empati', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-034', legacy_id: 'sk-06-00', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Participating in Self-Care', secondary: [{ domain: 'Social-Emotional', capability: 'Autonomy and Sense of Agency' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Kemandirian', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-035', legacy_id: 'sk-06-01', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: null },
    family: { primary_value: 'Kejujuran', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'kb-036', legacy_id: 'sk-06-02', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Emotional Regulation', secondary: [{ domain: 'Language & Communication', capability: 'Vocabulary Building' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Empati', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-037', legacy_id: 'sk-06-03', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Self-Awareness and Identity', secondary: [], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Syukur', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-038', legacy_id: 'sk-06-04', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [{ domain: 'Self-Regulation & Executive Function', capability: 'Impulse Control and Waiting' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Sabar', secondary: ['Berbagi'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-039', legacy_id: 'sk-06-05', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Participating in Routines and Chores', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Tanggung Jawab', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-040', legacy_id: 'sk-07-00', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Early Literacy and Storytelling', secondary: [{ domain: 'Social-Emotional', capability: 'Empathy and Understanding Others' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Cinta Ilmu', secondary: ['Kejujuran'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-041', legacy_id: 'sk-07-01', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Self-Awareness and Identity', secondary: [], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Syukur', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-042', legacy_id: 'sk-07-02', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Empathy and Understanding Others', secondary: [{ domain: 'Social-Emotional', capability: 'Social Interaction and Play with Others' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Berbagi', secondary: ['Kesederhanaan'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-043', legacy_id: 'sk-07-03', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Participating in Routines and Chores', secondary: [{ domain: 'Cognitive', capability: 'Curiosity and Exploration' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Tanggung Jawab', secondary: ['Sabar'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-044', legacy_id: 'sk-07-04', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Empathy and Understanding Others', secondary: [{ domain: 'Cognitive', capability: 'Symbolic and Pretend Thinking' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Empati', secondary: ['Keberanian'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-045', legacy_id: 'sk-07-05', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Emotional Regulation', secondary: [{ domain: 'Language & Communication', capability: 'Vocabulary Building' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Empati', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-046', legacy_id: 'sk-08-00', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [{ domain: 'Self-Regulation & Executive Function', capability: 'Following Simple Routines and Instructions' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Sabar', secondary: ['Hormat pada Sesama'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-047', legacy_id: 'sk-08-01', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [{ domain: 'Cognitive', capability: 'Symbolic and Pretend Thinking' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Hormat pada Sesama', secondary: ['Kejujuran'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-048', legacy_id: 'sk-08-02', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Expressive Communication', secondary: [{ domain: 'Cognitive', capability: 'Object Permanence and Memory' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Cinta Ilmu', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-049', legacy_id: 'sk-08-03', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Empathy and Understanding Others', secondary: [{ domain: 'Social-Emotional', capability: 'Social Interaction and Play with Others' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Berbagi', secondary: ['Empati'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-050', legacy_id: 'sk-08-04', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Focus and Attention Control', secondary: [{ domain: 'Cognitive', capability: 'Problem Solving' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Tanggung Jawab', secondary: ['Kemandirian'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-051', legacy_id: 'sk-08-05', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Autonomy and Sense of Agency', secondary: [{ domain: 'Gross Motor', capability: 'Balance and Coordination' }, { domain: 'Social-Emotional', capability: 'Social Interaction and Play with Others' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Keberanian', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-052', legacy_id: 'sk-09-00', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 60, max_months: 72 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Growing Independence in Daily Tasks', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Tanggung Jawab', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-053', legacy_id: 'sk-09-01', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 60, max_months: 72 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Impulse Control and Waiting', secondary: [{ domain: 'Cognitive', capability: 'Early Concepts (Shapes, Colors, Numbers, Letters)' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Kesederhanaan', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-054', legacy_id: 'sk-09-02', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 60, max_months: 72 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Empathy and Understanding Others', secondary: [{ domain: 'Social-Emotional', capability: 'Social Interaction and Play with Others' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Berbagi', secondary: ['Empati'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-055', legacy_id: 'sk-09-03', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 60, max_months: 72 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Self-Awareness and Identity', secondary: [{ domain: 'Self-Regulation & Executive Function', capability: 'Emotional Regulation' }], mapping_status: 'MAPPED', confidence: 'MEDIUM' },
    family: { primary_value: 'Kejujuran', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-056', legacy_id: 'sk-09-04', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 60, max_months: 72 },
    development: { primary_domain: 'Adaptive / Self-Help', primary_capability: 'Growing Independence in Daily Tasks', secondary: [{ domain: 'Self-Regulation & Executive Function', capability: 'Following Simple Routines and Instructions' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Kemandirian', secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
  {
    content_id: 'kb-057', legacy_id: 'sk-09-05', content_type: 'KEBIASAAN_BAIK',
    age_range: { min_months: 60, max_months: 72 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Expressive Communication', secondary: [{ domain: 'Social-Emotional', capability: 'Autonomy and Sense of Agency' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: 'Keberanian', secondary: ['Cinta Ilmu'] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY',
  },
];
