import type { ContentMetadata } from './types';

// Wawasan Tumbuh canonical metadata (64 items). Additive, runtime-inert. Generated — do not hand-edit.
export const WAWASAN_TUMBUH_METADATA: ContentMetadata[] = [
  {
    content_id: 'RL-0-3m-FM', legacy_id: 'RL-0-3m-FM', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Trunk and Postural Control', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-0-3m-KG', legacy_id: 'RL-0-3m-KG', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Attention and Focus', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-0-3m-BH', legacy_id: 'RL-0-3m-BH', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Expressive Communication', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-0-3m-SE', legacy_id: 'RL-0-3m-SE', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Attachment and Secure Relationship', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-0-3m-KS', legacy_id: 'RL-0-3m-KS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Child Health', topic: 'Sleep' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-0-3m-PS', legacy_id: 'RL-0-3m-PS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Parenting & Caregiving', topic: 'Responsive Caregiving & Stimulation' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-6m-FM', legacy_id: 'RL-3-6m-FM', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Locomotion and Moving Through Space', secondary: [{ domain: 'Fine Motor', capability: 'Grasping and Reaching' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-6m-KG', legacy_id: 'RL-3-6m-KG', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Cause-and-Effect Understanding', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-6m-BH', legacy_id: 'RL-3-6m-BH', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Expressive Communication', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-6m-SE', legacy_id: 'RL-3-6m-SE', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-6m-KS', legacy_id: 'RL-3-6m-KS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Child Health', topic: 'Nutrition & Feeding' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-6m-PS', legacy_id: 'RL-3-6m-PS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Parenting & Caregiving', topic: 'Responsive Caregiving & Stimulation' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-6-9m-FM', legacy_id: 'RL-6-9m-FM', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Locomotion and Moving Through Space', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-6-9m-KG', legacy_id: 'RL-6-9m-KG', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Object Permanence and Memory', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-6-9m-BH', legacy_id: 'RL-6-9m-BH', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Receptive Language', secondary: [{ domain: 'Language & Communication', capability: 'Gestures and Nonverbal Communication' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-6-9m-SE', legacy_id: 'RL-6-9m-SE', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Attachment and Secure Relationship', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-6-9m-KS', legacy_id: 'RL-6-9m-KS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Child Health', topic: 'Nutrition & Feeding' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-6-9m-PS', legacy_id: 'RL-6-9m-PS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Parenting & Caregiving', topic: 'Responsive Caregiving & Stimulation' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-9-12m-FM', legacy_id: 'RL-9-12m-FM', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Locomotion and Moving Through Space', secondary: [{ domain: 'Fine Motor', capability: 'Grasping and Reaching' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-9-12m-KG', legacy_id: 'RL-9-12m-KG', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Problem Solving', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-9-12m-BH', legacy_id: 'RL-9-12m-BH', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Expressive Communication', secondary: [{ domain: 'Language & Communication', capability: 'Gestures and Nonverbal Communication' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-9-12m-SE', legacy_id: 'RL-9-12m-SE', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Attachment and Secure Relationship', secondary: [{ domain: 'Social-Emotional', capability: 'Autonomy and Sense of Agency' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-9-12m-KS', legacy_id: 'RL-9-12m-KS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Child Health', topic: 'Nutrition & Feeding' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-9-12m-PS', legacy_id: 'RL-9-12m-PS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Parenting & Caregiving', topic: 'Positive Discipline & Boundaries' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-12-18m-FM', legacy_id: 'RL-12-18m-FM', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Locomotion and Moving Through Space', secondary: [{ domain: 'Fine Motor', capability: 'Early Mark-Making and Drawing' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-12-18m-KG', legacy_id: 'RL-12-18m-KG', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Symbolic and Pretend Thinking', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-12-18m-BH', legacy_id: 'RL-12-18m-BH', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Vocabulary Building', secondary: [{ domain: 'Language & Communication', capability: 'Receptive Language' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-12-18m-SE', legacy_id: 'RL-12-18m-SE', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Autonomy and Sense of Agency', secondary: [{ domain: 'Self-Regulation & Executive Function', capability: 'Emotional Regulation' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-12-18m-KS', legacy_id: 'RL-12-18m-KS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Child Health', topic: 'Nutrition & Feeding' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-12-18m-PS', legacy_id: 'RL-12-18m-PS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Parenting & Caregiving', topic: 'Positive Discipline & Boundaries' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-18-24m-FM', legacy_id: 'RL-18-24m-FM', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Balance and Coordination', secondary: [{ domain: 'Fine Motor', capability: 'Manipulating Objects' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-18-24m-KG', legacy_id: 'RL-18-24m-KG', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Symbolic and Pretend Thinking', secondary: [{ domain: 'Cognitive', capability: 'Early Concepts (Shapes, Colors, Numbers, Letters)' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-18-24m-BH', legacy_id: 'RL-18-24m-BH', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Vocabulary Building', secondary: [{ domain: 'Language & Communication', capability: 'Expressive Communication' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-18-24m-SE', legacy_id: 'RL-18-24m-SE', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Emotional Regulation', secondary: [{ domain: 'Social-Emotional', capability: 'Social Interaction and Play with Others' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-18-24m-KS', legacy_id: 'RL-18-24m-KS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Child Health', topic: 'Nutrition & Feeding' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-18-24m-PS', legacy_id: 'RL-18-24m-PS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Parenting & Caregiving', topic: 'Routines & Consistency' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-2-3y-FM', legacy_id: 'RL-2-3y-FM', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Balance and Coordination', secondary: [{ domain: 'Fine Motor', capability: 'Tool Use' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-2-3y-KG', legacy_id: 'RL-2-3y-KG', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Symbolic and Pretend Thinking', secondary: [{ domain: 'Cognitive', capability: 'Early Concepts (Shapes, Colors, Numbers, Letters)' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-2-3y-BH', legacy_id: 'RL-2-3y-BH', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Conversation and Turn-Taking', secondary: [{ domain: 'Language & Communication', capability: 'Vocabulary Building' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-2-3y-SE', legacy_id: 'RL-2-3y-SE', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Emotional Regulation', secondary: [{ domain: 'Social-Emotional', capability: 'Empathy and Understanding Others' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-2-3y-KS', legacy_id: 'RL-2-3y-KS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Child Health', topic: 'Nutrition & Feeding' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-2-3y-PS', legacy_id: 'RL-2-3y-PS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Parenting & Caregiving', topic: 'Routines & Consistency' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-4y-FM', legacy_id: 'RL-3-4y-FM', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Balance and Coordination', secondary: [{ domain: 'Fine Motor', capability: 'Tool Use' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-4y-KG', legacy_id: 'RL-3-4y-KG', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: 'Self-Regulation & Executive Function', primary_capability: 'Focus and Attention Control', secondary: [{ domain: 'Cognitive', capability: 'Symbolic and Pretend Thinking' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-4y-BH', legacy_id: 'RL-3-4y-BH', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Early Literacy and Storytelling', secondary: [{ domain: 'Language & Communication', capability: 'Expressive Communication' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-4y-SE', legacy_id: 'RL-3-4y-SE', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Social Interaction and Play with Others', secondary: [{ domain: 'Self-Regulation & Executive Function', capability: 'Emotional Regulation' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-4y-KS', legacy_id: 'RL-3-4y-KS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Child Health', topic: 'Growth & Physical Health' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-4y-PS', legacy_id: 'RL-3-4y-PS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Parenting & Caregiving', topic: 'Positive Discipline & Boundaries' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-4-5y-FM', legacy_id: 'RL-4-5y-FM', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: 'Gross Motor', primary_capability: 'Balance and Coordination', secondary: [{ domain: 'Fine Motor', capability: 'Early Mark-Making and Drawing' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-4-5y-KG', legacy_id: 'RL-4-5y-KG', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: 'Cognitive', primary_capability: 'Early Concepts (Shapes, Colors, Numbers, Letters)', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-4-5y-BH', legacy_id: 'RL-4-5y-BH', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: 'Language & Communication', primary_capability: 'Early Literacy and Storytelling', secondary: [{ domain: 'Language & Communication', capability: 'Vocabulary Building' }], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-4-5y-SE', legacy_id: 'RL-4-5y-SE', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: 'Social-Emotional', primary_capability: 'Empathy and Understanding Others', secondary: [], mapping_status: 'MAPPED', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: null, topic: null },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-4-5y-KS', legacy_id: 'RL-4-5y-KS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Child Health', topic: 'Growth & Physical Health' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-4-5y-PS', legacy_id: 'RL-4-5y-PS', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Parenting & Caregiving', topic: 'Positive Discipline & Boundaries' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-0-3m-DK', legacy_id: 'RL-0-3m-DK', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 0, max_months: 3 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Development Monitoring', topic: 'Screening & Milestones' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-6m-DK', legacy_id: 'RL-3-6m-DK', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 3, max_months: 6 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Development Monitoring', topic: 'Screening & Milestones' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-6-9m-DK', legacy_id: 'RL-6-9m-DK', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 6, max_months: 9 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Development Monitoring', topic: 'Screening & Milestones' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-9-12m-DK', legacy_id: 'RL-9-12m-DK', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 9, max_months: 12 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Development Monitoring', topic: 'Screening & Milestones' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-12-18m-DK', legacy_id: 'RL-12-18m-DK', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 12, max_months: 18 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Development Monitoring', topic: 'Screening & Milestones' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-18-24m-DK', legacy_id: 'RL-18-24m-DK', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 18, max_months: 24 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Development Monitoring', topic: 'Early Intervention & Special Needs' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-2-3y-DK', legacy_id: 'RL-2-3y-DK', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 24, max_months: 36 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Development Monitoring', topic: 'Developmental Concerns' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-3-4y-DK', legacy_id: 'RL-3-4y-DK', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 36, max_months: 48 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Development Monitoring', topic: 'Developmental Concerns' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-4-5y-DK', legacy_id: 'RL-4-5y-DK', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 48, max_months: 60 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Development Monitoring', topic: 'School Readiness & Transition' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
  {
    content_id: 'RL-5-6y-DK', legacy_id: 'RL-5-6y-DK', content_type: 'WAWASAN_TUMBUH',
    age_range: { min_months: 60, max_months: 72 },
    development: { primary_domain: null, primary_capability: null, secondary: [], mapping_status: 'NULL', confidence: 'HIGH' },
    family: { primary_value: null, secondary: [] },
    knowledge: { area: 'Development Monitoring', topic: 'School Readiness & Transition' },
    evidence: { type: null, strength: 'UNVERIFIED', source_ids: [] },
    governance: { expert_reviewer: null, review_status: 'NEEDS_REVIEW', review_date: null },
    readiness: 'READY_WITH_NULLS',
  },
];
